/*
Question : Given a string, WAM to return all its subsequences in an arraylist. A String is a subsequence of a
           given String that is generated by deleting some character of a given string without changing its order.
________________________________________________________________________________________________________________________
I/O = abc
O/P =  ,a,b,c,ab,bc,ac,abc
 */
import java.util.Scanner;
public class Main {
    
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String word;
        int initialization;
        System.out.println("Enter the word :");
        word = scanner.nextLine();
        System.out.println("Printing the result :");
        for (initialization = word.length() - 1; initialization >= 0; initialization--){
            System.out.print(" , " + word.charAt(initialization));
        }

        System.out.print(" , " + word);
    }
}